<?php
return array(
	'blog_name' => 'Booj Bytes',
	'blog_description' => 'This is the latest from Booj',
	'blog_url' => '/blog',
	'posts_per_page' => 10,
	'homepage_post_count' => 5,
	'main_photo' => array( 'width' => 870, 'height' => 470),
	'small_photo' => array( 'width' => 425, 'height' => 275),
	'photo_path' => '/uploads/blog',
	'similar_category_count' => 2,
	'similar_tag_count' => 2,
	'number_author_posts' => 4,
	'number_popular_posts' => 4,
	'number_popular_authors' => 5,
	'disgus_short_name' => 'booj',
	'disgus_key' => 'IQK2YYnkY3Ia3XcYaefF750eKpor3pwhhX8zQiWzONqYuLOAusomFYldhBhCVcov',
	'domain' => 'http://www.booj.com',
	'hide_these_authors_from_sidebar' => array(14),
);